@user = http://127.0.0.1:8000/api/users/

GET {{user}}

###

POST {{user}}
content-type: application/json

{
    "email": "vpupkin@yandex.ru",
    "username": "vasya.pupkin",
    "first_name": "Вася",
    "last_name": "Пупкин",
    "password": "Qwerty123"
}