version: '3.5'

volumes:
  pg_data:
  media:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: greger20/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/collected_static/
      - media:/app/media/

  frontend:
    image: greger20/foodgram_frontend
    depends_on:
      - backend
    volumes:
      - static_volume:/app/result_build/build/

  nginx:
    image: nginx:1.19.3
    depends_on:
      - backend
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/app/media/
