# Generated by Django 3.2.3 on 2023-07-14 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230714_0020'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientamount',
            name='amount_positive',
        ),
        migrations.RemoveConstraint(
            model_name='recipes',
            name='cooking_time_positive',
        ),
    ]
